PrintFromQueueDialogContent.listingsTab=TV listings
PrintFromQueueDialogContent.layoutTab=Layout
PrintFromQueueDialogContent.miscTab=Miscellaneous
PrintFromQueueDialogContent.dialogTitle=Print from queue

LayoutTab.columns=Columns
LayoutTab.columnsPerPage=Columns per page

ExtrasTab.programItem=Program item
ExtrasTab.showPluginMarkings=Show plugin markings

GeneralTab.emptyQueue=Empty queue after printing
GeneralTab.removeFromQueue=Remove from queue