
PrintPlugin.addToPrinterQueue      = Add to printer queue
PrintPlugin.defaultScheme          = Default Scheme
PrintPlugin.print                  = Print
PrintPlugin.printProgram           = Print program
PrintPlugin.printProgramInfo       = Print program info
PrintPlugin.printQueue             = Print queue
PrintPlugin.printdescription       = This plugin allows to print the program.
PrintPlugin.removeFromPrinterQueue = Remove from printer queue
PrintPlugin.emptyQueue             = Empty print queue

PrintPluginSettingsTab.markings = Highlighting
PrintPluginSettingsTab.preview=Preview
PrintPluginSettingsTab.paperformat=Paper Format
PrintPluginSettingsTab.printer=Printer
PrintPluginSettingsTab.fonts=Fonts
PrintPluginSettingsTab.antialiasing=Antialiasing
PrintPluginSettingsTab.appearance=Appearance
PrintPluginSettingsTab.toolbarPos=Placement of printer actions
PrintPluginSettingsTab.toolbar=Toolbar
PrintPluginSettingsTab.right=Right (Trailing)
PrintPluginSettingsTab.top=Top
PrintPluginSettingsTab.left=Left
PrintPluginSettingsTab.bottom=Bottom
PrintPluginSettingsTab.defaults=Defaults
PrintPluginSettingsTab.changes=Changes
PrintPluginSettingsTab.licenses=Licenses
PrintPluginSettingsTab.contextmenu=Context menu

PrintPluginSettingsTab.CUSTOM=Custom
PrintPluginSettingsTab.DEFAULT=Default
PrintPluginSettingsTab.MINIMUM=Minimum
PrintPluginSettingsTab.NARROW=Narrow
PrintPluginSettingsTab.NORMAL=Normal

PrintPluginSettingsTab.landscape=Landscape
PrintPluginSettingsTab.portrait=Portrait
PrintPluginSettingsTab.pageOrientation=Page orientation
PrintPluginSettingsTab.pageMargins=Page margins
PrintPluginSettingsTab.paperFormat=Paper format
PrintPluginSettingsTab.printProgramInfoWithoutDialog=Add Print program info directly to context menu (TODO)
PrintPluginSettingsTab.showImageableArea=Show imageable area
PrintPluginSettingsTab.otherSettings=Other settings
PrintPluginSettingsTab.default=Standard
PrintPluginSettingsTab.system=System
PrintPluginSettingsTab.previewFonts=Preview fonts in UI elements
PrintPluginSettingsTab.never=Never
PrintPluginSettingsTab.ever=Always
PrintPluginSettingsTab.mouseOver=On mouse over
PrintPluginSettingsTab.printPageNumbers=Print page numbers
PrintPluginSettingsTab.footer=Footer
PrintPluginSettingsTab.header=Header
PrintPluginSettingsTab.font=Font
PrintPluginSettingsTab.foregroundColor=Foreground Color
PrintPluginSettingsTab.backgroundColor=Background Color
PrintPluginSettingsTab.paddings=Paddings
PrintPluginSettingsTab.margins=Margins
PrintPluginSettingsTab.cm=cm
PrintPluginSettingsTab.inch=inch
PrintPluginSettingsTab.systemPrinter=System printer
PrintPluginSettingsTab.systemFont=System font
PrintPluginSettingsTab.integrateExtras=Integrate Extras in Layout settings