PluginSettings.error.write=Saving settings for plugin {0} failed!\n({1})
PluginSettings.error.load=Loading settings for plugin {0} failed!\n({1})
PluginSettings.error.data.write=Saving data for plugin {0} failed.\n({1})
PluginSettings.error.data.load=Loading data for plugin {0} failed.\n({1})