
SimpleMarkerPlugin.chooseIcon                          = Choose icon for {0}
SimpleMarkerPlugin.days                                = Days
SimpleMarkerPlugin.default                             = Default list
SimpleMarkerPlugin.deletedPrograms                     = Deleted programs
SimpleMarkerPlugin.deletedProgramsMsg                  = During the data update the following programs were deleted:
SimpleMarkerPlugin.description                         = A simple marker plugin
SimpleMarkerPlugin.extendedMark                        = Mark programs of filter...
SimpleMarkerPlugin.filter                              = Filter:
SimpleMarkerPlugin.filterErrorMessage                  = The mark list that is used for the filter component '{0}' was deleted.\nPlease correct your filter configuration!
SimpleMarkerPlugin.filterText                          = Contained on a list of Marker plugin
SimpleMarkerPlugin.grouping.both                       = By title and date
SimpleMarkerPlugin.grouping.date                       = By date
SimpleMarkerPlugin.grouping.grouping                   = Grouping
SimpleMarkerPlugin.grouping.title                      = By title
SimpleMarkerPlugin.iconFiles                           = Icon files {0}
SimpleMarkerPlugin.iconSize                            = The icon has to 16x16 in size.
SimpleMarkerPlugin.list.export                         = Add to '{0}'
SimpleMarkerPlugin.list.export.both                    = Add/Remove to/from '{0}'
SimpleMarkerPlugin.list.export.remove                  = Remove from '{0}'
SimpleMarkerPlugin.list.mark                           = on <i><b>{0}</b></i>
SimpleMarkerPlugin.list.mark.old                       = on '{0}'
SimpleMarkerPlugin.list.name                           = Simple Marker
SimpleMarkerPlugin.list.programs                       = List programs
SimpleMarkerPlugin.list.titles                         = List for program titles
SimpleMarkerPlugin.list.unmark                         = Remove from <i><b>{0}</b></i>
SimpleMarkerPlugin.list.unmark.old                     = Remove from '{0}'
SimpleMarkerPlugin.mark                                = Mark\u2026
SimpleMarkerPlugin.markList                            = Mark lists
SimpleMarkerPlugin.markProgram                         = Mark program
SimpleMarkerPlugin.markedOn                            = Marked on 
SimpleMarkerPlugin.name                                = Markers
SimpleMarkerPlugin.programList                         = Program list
SimpleMarkerPlugin.scrollToFirstNotExpired             = Scroll to first not expired program.
SimpleMarkerPlugin.selectedList                        = Currently selected list
SimpleMarkerPlugin.settings.add                        = Add new list
SimpleMarkerPlugin.settings.changeIcon                 = Change list icon
SimpleMarkerPlugin.settings.delete                     = Delete selected list(s)
SimpleMarkerPlugin.settings.eventType                  = <html>Supported receive<br>events\u00B2</html>
SimpleMarkerPlugin.settings.eventType.added            = Added
SimpleMarkerPlugin.settings.eventType.all              = Added and removed
SimpleMarkerPlugin.settings.eventType.removed          = Removed
SimpleMarkerPlugin.settings.eventType.undefined        = Undefined
SimpleMarkerPlugin.settings.eventTypeHelp              = \u00B2 Which type of received programs are processed by the list
SimpleMarkerPlugin.settings.higherMedium               = Higher Medium
SimpleMarkerPlugin.settings.highlightingPriority       = Color/priority
SimpleMarkerPlugin.settings.icon                       = Icon
SimpleMarkerPlugin.settings.importance.default         = Default
SimpleMarkerPlugin.settings.importance.higherMedium    = Higher medium
SimpleMarkerPlugin.settings.importance.lowerMedium     = Lower medium
SimpleMarkerPlugin.settings.importance.max             = Maximum
SimpleMarkerPlugin.settings.importance.medium          = Medium
SimpleMarkerPlugin.settings.importance.min             = Mininum
SimpleMarkerPlugin.settings.informAboutDeletedPrograms = \u00B9cInform about programs of that list that were deleted during a data update 
SimpleMarkerPlugin.settings.informDelProgramsForList   = <html>Show removed\nprograms\u00B9</html>
SimpleMarkerPlugin.settings.jump.time                  = Jump to time on currently shown day
SimpleMarkerPlugin.settings.jump.timeNext              = Jump to next occurrence of time from current view
SimpleMarkerPlugin.settings.list                       = Mark list
SimpleMarkerPlugin.settings.listName                   = List {0}
SimpleMarkerPlugin.settings.markPriority               = Highlighting priority
SimpleMarkerPlugin.settings.noPriority                 = None
SimpleMarkerPlugin.settings.prioHelp                   = The highlighting priority is used for selecting the higlighting color. The highlighting colors of the priorities can be change in the <a href="#link1">highlighting settings</a>. If a program is highlighted by more than one plugin/list the color with the highest priority given for the program by the highlighting plugins/lists is used.<br>\r\n<br>\r\nThe selected importance is used to determinate the transparency of a program. It's calculated over all plugins/lists as mean value. Lower importance leads to higher transparency. This works only if the plugins are allowed to set the transparency at <a href="#link2">program panel settings</a>.
SimpleMarkerPlugin.settings.programImportance          = Program importance
SimpleMarkerPlugin.settings.react.date                 = Date
SimpleMarkerPlugin.settings.react.filter               = Filter
SimpleMarkerPlugin.settings.react.label                = Tab reacts on following actions in main window
SimpleMarkerPlugin.settings.react.time                 = Time
SimpleMarkerPlugin.settings.sendToNone                 = None
SimpleMarkerPlugin.settings.sendToPlugin               = Send to plugin
SimpleMarkerPlugin.settings.sendToPlugins              = {0} Plugins
SimpleMarkerPlugin.settings.showDateSeparator          = Show date separator in marked programs list
SimpleMarkerPlugin.showInContext                       = For more than one list, show actions in submenu of TV-Browser context menu
SimpleMarkerPlugin.tooltip.deletePrograms              = Delete all/selected progams
SimpleMarkerPlugin.tooltip.deleteTitles                = Delete programs with selected titles/all programs
SimpleMarkerPlugin.tooltip.send                        = Send programs to other plugins
SimpleMarkerPlugin.tooltip.settings                    = Open settings
SimpleMarkerPlugin.tooltip.undo                        = Undo
SimpleMarkerPlugin.unmark                              = Remove marking
SimpleMarkerPlugin.unmarkall                           = Just unmark all
