PrintProgramInfoDialogContent.font       		= Font
PrintProgramInfoDialogContent.order      		= Info fields and order
PrintProgramInfoDialogContent.printImage 		= Print image
PrintProgramInfoDialogContent.title      		= Print program info
PrintProgramInfoDialogContent.printPluginIcons = Print plugin icons
PrintProgramInfoDialogContent.layoutTab=Layout