
ErrorHandler.copyToClipboard = Copy to clipboard
ErrorHandler.details         = Details
ErrorHandler.no              = No
ErrorHandler.yes             = Yes

MonitoringErrorStream.error.1 = An unhandled error has occured

UACStarter.noUac = No UAC useable
