
CapturePlugin.CapturePlugin                  = Recording control
CapturePlugin.CreateDevice                   = Please create device first!
CapturePlugin.Desc                           = Starts an external program with configurable parameters
CapturePlugin.configure                      = Configure '{0}'
CapturePlugin.date                           = Date
CapturePlugin.deletedText                    = The data was changed and the following programs were deleted:
CapturePlugin.deletedTitle                   = Deleted programs
CapturePlugin.device                         = Device
CapturePlugin.exportList                     = Export list
CapturePlugin.quick                          = Quick scheduling
CapturePlugin.record                         = Record
CapturePlugin.remove                         = Remove recording

CapturePluginData.ProblemDevice = Problems while loading device {0}.

CapturePluginDialog.Title = Recording control - Settings

CapturePluginPanel.Devices                   = Devices
CapturePluginPanel.Global                    = Global Settings
CapturePluginPanel.ProgramList               = List of recordings
CapturePluginPanel.highlight.multiple        = By multiple devices:
CapturePluginPanel.highlight.single          = By one device:
CapturePluginPanel.showDirectlyInContextMenu = Show devices directly in context menu of TV-Browser.
CapturePluginPanel.showOnTop                 = Show additional commands (if any) on top of context menu
CapturePluginPanel.showRemovedPrograms       = Show dialog with removed programs after data update.

CapturePluginSettingsTab.Title = Recording control
