EPGdataReset.name            = EPGdataReset
EPGdataReset.desc            = Resets the data cache of the EPGfree and EPGdonate data plugins.
EPGdataReset.action          = Reset data cache now
EPGdataReset.success         = Data cache cleared successfully
EPGdataReset.error           = Data cache could not be cleared completely
EPGdataReset.nodatadirectory = Data directory could not be found.\n\nData cache was not deleted.
EPGdataReset.result          = Result of clearing data cache
EPGdataReset.autoReset       = Always reset data cache before data update