
LimitationConfiguration.day.daily     = Daily
LimitationConfiguration.day.friday    = Friday
LimitationConfiguration.day.monday    = Monday
LimitationConfiguration.day.saturday  = Saturday
LimitationConfiguration.day.sunday    = Sunday
LimitationConfiguration.day.thursday  = Thursday
LimitationConfiguration.day.tuesday   = Tuesday
LimitationConfiguration.day.wednesday = Wednesday
LimitationConfiguration.day.weekday   = Weekday (mon-fri)
LimitationConfiguration.day.weekend   = Weekend (sat & sun)
